### ISSUE TITLE
There is a dashboard with a discontinuous time series of data

### ISSUE THREAD

**Issue by LynnTsang** [footprintanalytics/footbase#270]
![image](https://user-images.githubusercontent.com/121166680/210298495-9479fb91-5712-4f79-be9f-7109c64ca7aa.png)
https://www.footprint.network/@gF5qifSNV4/Hooked-Protocol-Wild-Cash-Overview-Duplicate

**Comment by sefigi** [comment]
The contracts of this agreement did not have any transactions during this period
