### ISSUE TITLE
price of eth in 5 mins during Dec 23, 2022 not change a bit.

### ISSUE THREAD

**Issue by no7dw** [footprintanalytics/footbase#271]
**Describe the bug**
price of eth in 5 mins since Dec 23, 2022 not change a bit.

**To Reproduce**
1. Go to https://www.footprint.network/chart/eth-price-5min-last-3D-fp-35583

**Expected behavior**

**Screenshots**
 
![image](https://user-images.githubusercontent.com/2989631/210301272-6ff8dadf-08b4-4563-8dfb-db9d4d4b05ab.png)
 ![image](https://user-images.githubusercontent.com/2989631/210305408-4b234345-de9b-4373-9147-96dcaf400a56.png)

**Comment by alex-klg** [comment]
At that time, the token price system is abnormal, not timely output coin price, has been fixed
