### ISSUE TITLE
Please ask if http://playground.footprint.network:8123/ cannot be accessed

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#276]
**Describe the bug**

Please ask if http://playground.footprint.network:8123/ cannot be accessed

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/210495202-48390765-39b0-4b9d-a915-d0c8ea2492e3.png)

**Comment by Hala2Madrid** [comment]
This playground is an experimental product, as the team resources adjust, the product is temporarily closed.
