### ISSUE TITLE
nft_order table data exception, missing data from 2022-12-14 to 2023-01-05

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#284]
**Describe the bug**
nft_order table data exception, missing data from 2022-12-14 to 2023-01-05
**To Reproduce**
https://opensea.io/assets/ethereum/0x23581767a106ae21c074b2276d25e5c3e136a68b/3304
```
select * 
from nft_orders 
where 
  marketplace_slug = 'opensea' 
  and collection_contract_address = '0x23581767a106ae21c074b2276d25e5c3e136a68b' 
  and nft_token_id = '3304'
  and created_at > date('2022-12-01')
```

**Screenshots**

**Comment by Himkid19** [comment]
the unstable service of the message queue results in data loss and has put the missing time message is uploaded to the queue, waitting for consumption.
