### ISSUE TITLE
UI problem when editing chart.

### ISSUE THREAD

**Issue by dumpling1004** [footprintanalytics/footbase#287]
**Describe the bug**
UI problem when editing chart

**To Reproduce**
When I try to use filter after select data set. The explainer keep in window. 
Equipment: M2 Macbook Air w/ Mac OS 12.4 w/ chrome. 

**Screenshots**
![image](https://user-images.githubusercontent.com/116546874/210715233-8ebe55fc-0419-45bb-b6bc-b2da1d33b82f.png)

**Comment by sefigi** [comment]
Move the mouse over it and then move it away
