### ISSUE TITLE
Dashboard 的“Add Series” 功能无法使用

### ISSUE THREAD

**Issue by Sulliww** [footprintanalytics/footbase#289]
Dashboard 的“Add Series” 功能无法使用
![image](https://user-images.githubusercontent.com/121418647/210728139-ae6c3c87-4481-46a4-b4c7-104da4e64914.png)
![image](https://user-images.githubusercontent.com/121418647/210728164-80bd8bf1-7ebc-429f-8498-03a80e33466d.png)

**Comment by ydpzg** [comment]
The bug has been solved, the parameters were passed incorrectly.
