### ISSUE TITLE
defi_protocol_daily_stats data is abnormal

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#298]
**Describe the bug**
defi_protocol_daily_stats has a problem with the data on January 7th and 8th. The protocol data of Ethereum before the 6th is still 451, and the protocol number of the data on the 7th/8th is only 5.
**To Reproduce**
```
SELECT 
on_date ,
"chain",
sum("tvl") AS "TVL",
count(distinct "protocol_name") AS "Protocols"
FROM "defi_protocol_daily_stats"
GROUP BY "chain",on_date
order by on_date desc
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/211250914-8b9d5046-a2e6-4f7e-b3df-9503c1ee6429.png)

**Comment by meicanhong** [comment]
The underlying data defi_protocol_slug was not updated, it has been fixed
