### ISSUE TITLE
The data in the ud_us_market_indexes table will not be updated on December 19, 2022

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#300]
**Describe the bug**
The data in the ud_us_market_indexes table will not be updated on December 19, 2022
**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/211269441-ef3a4ed6-e368-4104-a5e7-7c989cab6657.png)

**Comment by Rosen529** [comment]
Migrating airflow legacy bugs
