### ISSUE TITLE
Floor Price Data Exceptions

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#305]
**Describe the bug** The floor price data of ‘0x306b1ea3ecdf94aB739F1910bbda052Ed4A9f949’ this collection address is very different from the price data of OpenSea
**To Reproduce**
**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/211494423-cde3e528-6be2-444b-98c5-b2c1524454b6.png)
![image](https://user-images.githubusercontent.com/44665855/211494872-7dc5b8cd-abc5-4709-a36f-63e1cf327558.png)

**Comment by Hala2Madrid** [comment]
Depending on the data dictionary of nft_collection_daily_stats: https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=nft_collection_daily_stats

The floor price methodology of Footprint is calculated based on the listing price from multiple marketplaces and traded price of each collection; outliers from wash-trading were excluded.

The listing price is collected from 3rd-party data sources, when it's not stable, we use trading price instead.
