### ISSUE TITLE
Footprint NFT Modle  Data Exceptions

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#307]
**Describe the bug**
Footprint NFT Modle  Data Exceptions
[link](https://nft.footprint.network/nft/collection) 
**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/44665855/211525893-b490459a-1cc5-4e5c-acc9-d8c4b6e039d0.png)

**Comment by NoKnow606** [comment]
System configuration causes dirty data to exist in the cache, thus making it inaccessible
