### ISSUE TITLE
Axie history data exceptions

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#309]
**Describe the bug**
Checking the Axie platform data, we found that our historical data and dapp's historical data between 2022-01-31 - 2022-06-05 do not match, and there is a big difference
**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/211714105-ac4cc46f-cc46-4401-9813-1f4a9ce34aca.png)
![image](https://user-images.githubusercontent.com/44665855/211714600-b9c0be94-9c89-4207-a7bc-a2e93d053308.png)

**Comment by Rosen529** [comment]
Contracts are not fully included, fixed
