### ISSUE TITLE
Cronos chain raw data duplication

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#315]
**Describe the bug**
I realised that for certain hashes, there are duplicated events in the DB.
e.g. for tx '0xc999809d754931a4366d041d358a1235dd468388b11d952c21c490755eb88a02'
There should be a total of 5 events (5 rows), but the cronos_logs DB is showcasing duplicated records, making it a total of 10 events.
**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/211758461-4b4ed0e6-170c-4552-9964-4621f2dafe5b.png)

**Comment by RryanLH** [comment]
Reason:
Because the node data is abnormal, so we async the wrong data

Fix Solution:
Change the node provider and fix the wrong data.Related checks and monitoring will also be added.
