### ISSUE TITLE
 Dashboard filter error

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#318]
I keep getting this error message whenever i try to adjust my date filter to include more graphs.

![image](https://user-images.githubusercontent.com/44665855/211989743-f4ff2ac1-23c7-492f-8a12-c2b0994e87a2.png)

will there be an issue when there's too many charts?
https://www.footprint.network/@cloudr3n/DFKChain-Statistics this is the dashboard

**Comment by ydpzg** [comment]
Because this dashboard added the image component, there are bugs, has been fixed
