### ISSUE TITLE
gamefi protocol daily stats Splinterlands protocol logo link is empty

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footbase#338]
**Describe the bug**
gamefi protocol daily stats Splinterlands protocol logo link is empty
**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/212801289-83a1ec63-579a-480a-8102-e6b1f7097993.png)

**Comment by Rosen529** [comment]
Incremental program runtime data not ready
