### ISSUE TITLE
Experience problems with Solana

### ISSUE THREAD

**Issue by dumpling1004** [footprintanalytics/footbase#341]
Purpose: want to check existing collection with recent mints. 

Facing some problems: for example this contract
GhQZTjrrLmv1j9SzMKZJTq6zXfNk8g9GAGTWQbf4GFk1

gives empty data on https://docs.footprint.network/reference/get_nft-collection-transfers

**Comment by sefigi** [comment]
GhQZTjrrLmv1j9SzMKZJTq6zXfNk8g9GAGTWQbf4GFk1 This address is not a nft collection address
You can refer to the following links and screenshots
https://solscan.io/token/Buwq1poDoLxrnADbm6oZgaLnyLu2cW6g5fS5Pfat9J78
![image](https://user-images.githubusercontent.com/44665855/212841581-73f5ed0a-ca28-493a-aa70-9e80b3df1d62.png)
