### ISSUE TITLE
are there any rate limits? should my script wait between requests?

### ISSUE THREAD

**Issue by dumpling1004** [footprintanalytics/footbase#342]
because now I get failed{ "message":"API rate limit exceeded" }

**Comment by sefigi** [comment]
Yes , for more details you can take a look at the pricing page 
 https://www.footprint.network/pricing?type=data-api
![image](https://user-images.githubusercontent.com/44665855/212842310-0d795484-3792-4cac-a041-6768a4a8793e.png)
